kind: pipeline
name: default

steps:
  
- name: Deploy Single
  image: alpine
  commands:
  - apk --update add curl openssh openssh-client git
  - curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/0.13.0/terraform_0.13.0_linux_amd64.zip"
  - unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
  - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
  - terraform -v
  - terraform init 
  - terraform validate
