kind: pipeline
name: default

steps:
  
- name: Deploy
  image: alpine
  environment:
    TF_VAR_auth_token:
      from_secret: TF_VAR_esxi_host_count
    TF_VAR_count_x86:
      from_secret: TF_VAR_count_x86
    TF_VAR_count_arm:
      from_secret: TF_VAR_count_arm
    TF_VAR_project_id:
      from_secret: TF_VAR_project_id
  commands:
  - curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/0.12.2/terraform_0.12.2_linux_amd64.zip"
  - unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
  - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
  - terraform -v
  - terraform init 
  - terraform validate
