# Defaults should be inherited from top-level project consuming the module
variable "vcenter_host" {}
variable "vcenter_admin" {}
variable "vcenter_password" {}
variable "nsuser" {}
variable "nsdomain" {}
variable "cluster_name" {}
variable "namespace" {}
variable "storagepolicy" {}
variable "storagelimit" {}
variable "cp_vm_network" {}
variable "cp_subnet_mask" {}
variable "cp_gateway_ip" {}
variable "starting_ip" {}
variable "dns_server" {}
variable "ntp_server" {}
variable "storage_policy_name" {}
variable "egress_starting_ip" {}
variable "ingress_starting_ip" {}